# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := t1
DEFS_Default :=

# Flags passed to all source files.
CFLAGS_Default := \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Default :=

# Flags passed to only C++ files.
CFLAGS_CC_Default :=

INCS_Default := \
	-Itests \
	-I. \
	-Isrc/core

OBJS := \
	$(obj).target/$(TARGET)/tests/t1.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(builddir)/lib.target/libjet.so $(obj).target/libjet.so

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := \
	-pthread \
	-pthread \
	-Wl,-rpath=\$$ORIGIN/lib.target/ \
	-Wl,-rpath-link=\$(builddir)/lib.target/

LIBS := \
	-lrt \
	-ldl

$(builddir)/t1: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/t1: LIBS := $(LIBS)
$(builddir)/t1: LD_INPUTS := $(OBJS) $(obj).target/libjet.so
$(builddir)/t1: TOOLSET := $(TOOLSET)
$(builddir)/t1: $(OBJS) $(obj).target/libjet.so FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/t1
# Add target alias
.PHONY: t1
t1: $(builddir)/t1

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/t1

